<?php
/**
 * CountriesSeeder.php
 *
 * @copyright  2022 beikeshop.com - All Rights Reserved
 * @link       https://beikeshop.com
 * @author     Edward Yang <yangjin@guangda.work>
 * @created    2022-09-05 19:42:42
 * @modified   2022-09-05 19:42:42
 */

namespace Database\Seeders;

use Beike\Models\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = $this->getItems();

        if ($items) {
            Country::query()->truncate();
            Country::query()->insert(collect($items)->map(function ($item) {
                $item['created_at'] = now();
                $item['updated_at'] = now();
                return $item;
            })->toArray());
        }
    }


    public function getItems()
    {
        return [
            [
                "id" => 1,
                "name" => "Afghanistan",
                "code" => "AF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 2,
                "name" => "Albania",
                "code" => "AL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 3,
                "name" => "Algeria",
                "code" => "DZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 4,
                "name" => "American Samoa",
                "code" => "AS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 5,
                "name" => "Andorra",
                "code" => "AD",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 6,
                "name" => "Angola",
                "code" => "AO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 7,
                "name" => "Anguilla",
                "code" => "AI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 8,
                "name" => "Antarctica",
                "code" => "AQ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 9,
                "name" => "Antigua and Barbuda",
                "code" => "AG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 10,
                "name" => "Argentina",
                "code" => "AR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 11,
                "name" => "Armenia",
                "code" => "AM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 12,
                "name" => "Aruba",
                "code" => "AW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 13,
                "name" => "Australia",
                "code" => "AU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 14,
                "name" => "Austria",
                "code" => "AT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 15,
                "name" => "Azerbaijan",
                "code" => "AZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 16,
                "name" => "Bahamas",
                "code" => "BS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 17,
                "name" => "Bahrain",
                "code" => "BH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 18,
                "name" => "Bangladesh",
                "code" => "BD",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 19,
                "name" => "Barbados",
                "code" => "BB",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 20,
                "name" => "Belarus",
                "code" => "BY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 21,
                "name" => "Belgium",
                "code" => "BE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 22,
                "name" => "Belize",
                "code" => "BZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 23,
                "name" => "Benin",
                "code" => "BJ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 24,
                "name" => "Bermuda",
                "code" => "BM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 25,
                "name" => "Bhutan",
                "code" => "BT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 26,
                "name" => "Bolivia",
                "code" => "BO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 27,
                "name" => "Bosnia and Herzegovina",
                "code" => "BA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 28,
                "name" => "Botswana",
                "code" => "BW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 29,
                "name" => "Bouvet Island",
                "code" => "BV",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 30,
                "name" => "Brazil",
                "code" => "BR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 31,
                "name" => "British Indian Ocean Territory",
                "code" => "IO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 32,
                "name" => "Brunei Darussalam",
                "code" => "BN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 33,
                "name" => "Bulgaria",
                "code" => "BG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 34,
                "name" => "Burkina Faso",
                "code" => "BF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 35,
                "name" => "Burundi",
                "code" => "BI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 36,
                "name" => "Cambodia",
                "code" => "KH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 37,
                "name" => "Cameroon",
                "code" => "CM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 38,
                "name" => "Canada",
                "code" => "CA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 39,
                "name" => "Cape Verde",
                "code" => "CV",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 40,
                "name" => "Cayman Islands",
                "code" => "KY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 41,
                "name" => "Central African Republic",
                "code" => "CF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 42,
                "name" => "Chad",
                "code" => "TD",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 43,
                "name" => "Chile",
                "code" => "CL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 44,
                "name" => "中国",
                "code" => "CN",
                "sort_order" => -1,
                "status" => 1,
            ],
            [
                "id" => 45,
                "name" => "Christmas Island",
                "code" => "CX",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 46,
                "name" => "Cocos (Keeling) Islands",
                "code" => "CC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 47,
                "name" => "Colombia",
                "code" => "CO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 48,
                "name" => "Comoros",
                "code" => "KM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 49,
                "name" => "Congo",
                "code" => "CG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 50,
                "name" => "Cook Islands",
                "code" => "CK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 51,
                "name" => "Costa Rica",
                "code" => "CR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 52,
                "name" => "Cote D'Ivoire",
                "code" => "CI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 53,
                "name" => "Croatia",
                "code" => "HR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 54,
                "name" => "Cuba",
                "code" => "CU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 55,
                "name" => "Cyprus",
                "code" => "CY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 56,
                "name" => "Czech Republic",
                "code" => "CZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 57,
                "name" => "Denmark",
                "code" => "DK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 58,
                "name" => "Djibouti",
                "code" => "DJ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 59,
                "name" => "Dominica",
                "code" => "DM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 60,
                "name" => "Dominican Republic",
                "code" => "DO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 61,
                "name" => "East Timor",
                "code" => "TL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 62,
                "name" => "Ecuador",
                "code" => "EC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 63,
                "name" => "Egypt",
                "code" => "EG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 64,
                "name" => "El Salvador",
                "code" => "SV",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 65,
                "name" => "Equatorial Guinea",
                "code" => "GQ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 66,
                "name" => "Eritrea",
                "code" => "ER",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 67,
                "name" => "Estonia",
                "code" => "EE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 68,
                "name" => "Ethiopia",
                "code" => "ET",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 69,
                "name" => "Falkland Islands (Malvinas)",
                "code" => "FK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 70,
                "name" => "Faroe Islands",
                "code" => "FO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 71,
                "name" => "Fiji",
                "code" => "FJ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 72,
                "name" => "Finland",
                "code" => "FI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 74,
                "name" => "France, Metropolitan",
                "code" => "FR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 75,
                "name" => "French Guiana",
                "code" => "GF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 76,
                "name" => "French Polynesia",
                "code" => "PF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 77,
                "name" => "French Southern Territories",
                "code" => "TF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 78,
                "name" => "Gabon",
                "code" => "GA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 79,
                "name" => "Gambia",
                "code" => "GM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 80,
                "name" => "Georgia",
                "code" => "GE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 81,
                "name" => "Germany",
                "code" => "DE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 82,
                "name" => "Ghana",
                "code" => "GH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 83,
                "name" => "Gibraltar",
                "code" => "GI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 84,
                "name" => "Greece",
                "code" => "GR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 85,
                "name" => "Greenland",
                "code" => "GL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 86,
                "name" => "Grenada",
                "code" => "GD",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 87,
                "name" => "Guadeloupe",
                "code" => "GP",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 88,
                "name" => "Guam",
                "code" => "GU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 89,
                "name" => "Guatemala",
                "code" => "GT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 90,
                "name" => "Guinea",
                "code" => "GN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 91,
                "name" => "Guinea-Bissau",
                "code" => "GW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 92,
                "name" => "Guyana",
                "code" => "GY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 93,
                "name" => "Haiti",
                "code" => "HT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 94,
                "name" => "Heard and Mc Donald Islands",
                "code" => "HM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 95,
                "name" => "Honduras",
                "code" => "HN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 97,
                "name" => "Hungary",
                "code" => "HU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 98,
                "name" => "Iceland",
                "code" => "IS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 99,
                "name" => "India",
                "code" => "IN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 100,
                "name" => "Indonesia",
                "code" => "ID",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 101,
                "name" => "Iran (Islamic Republic of)",
                "code" => "IR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 102,
                "name" => "Iraq",
                "code" => "IQ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 103,
                "name" => "Ireland",
                "code" => "IE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 104,
                "name" => "Israel",
                "code" => "IL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 105,
                "name" => "Italy",
                "code" => "IT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 106,
                "name" => "Jamaica",
                "code" => "JM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 107,
                "name" => "Japan",
                "code" => "JP",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 108,
                "name" => "Jordan",
                "code" => "JO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 109,
                "name" => "Kazakhstan",
                "code" => "KZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 110,
                "name" => "Kenya",
                "code" => "KE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 111,
                "name" => "Kiribati",
                "code" => "KI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 112,
                "name" => "North Korea",
                "code" => "KP",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 113,
                "name" => "South Korea",
                "code" => "KR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 114,
                "name" => "Kuwait",
                "code" => "KW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 115,
                "name" => "Kyrgyzstan",
                "code" => "KG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 116,
                "name" => "Lao People's Democratic Republic",
                "code" => "LA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 117,
                "name" => "Latvia",
                "code" => "LV",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 118,
                "name" => "Lebanon",
                "code" => "LB",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 119,
                "name" => "Lesotho",
                "code" => "LS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 120,
                "name" => "Liberia",
                "code" => "LR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 121,
                "name" => "Libyan Arab Jamahiriya",
                "code" => "LY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 122,
                "name" => "Liechtenstein",
                "code" => "LI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 123,
                "name" => "Lithuania",
                "code" => "LT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 124,
                "name" => "Luxembourg",
                "code" => "LU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 126,
                "name" => "FYROM",
                "code" => "MK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 127,
                "name" => "Madagascar",
                "code" => "MG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 128,
                "name" => "Malawi",
                "code" => "MW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 129,
                "name" => "Malaysia",
                "code" => "MY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 130,
                "name" => "Maldives",
                "code" => "MV",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 131,
                "name" => "Mali",
                "code" => "ML",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 132,
                "name" => "Malta",
                "code" => "MT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 133,
                "name" => "Marshall Islands",
                "code" => "MH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 134,
                "name" => "Martinique",
                "code" => "MQ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 135,
                "name" => "Mauritania",
                "code" => "MR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 136,
                "name" => "Mauritius",
                "code" => "MU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 137,
                "name" => "Mayotte",
                "code" => "YT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 138,
                "name" => "Mexico",
                "code" => "MX",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 139,
                "name" => "Micronesia, Federated States of",
                "code" => "FM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 140,
                "name" => "Moldova, Republic of",
                "code" => "MD",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 141,
                "name" => "Monaco",
                "code" => "MC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 142,
                "name" => "Mongolia",
                "code" => "MN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 143,
                "name" => "Montserrat",
                "code" => "MS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 144,
                "name" => "Morocco",
                "code" => "MA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 145,
                "name" => "Mozambique",
                "code" => "MZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 146,
                "name" => "Myanmar",
                "code" => "MM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 147,
                "name" => "Namibia",
                "code" => "NA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 148,
                "name" => "Nauru",
                "code" => "NR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 149,
                "name" => "Nepal",
                "code" => "NP",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 150,
                "name" => "Netherlands",
                "code" => "NL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 151,
                "name" => "Netherlands Antilles",
                "code" => "AN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 152,
                "name" => "New Caledonia",
                "code" => "NC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 153,
                "name" => "New Zealand",
                "code" => "NZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 154,
                "name" => "Nicaragua",
                "code" => "NI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 155,
                "name" => "Niger",
                "code" => "NE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 156,
                "name" => "Nigeria",
                "code" => "NG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 157,
                "name" => "Niue",
                "code" => "NU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 158,
                "name" => "Norfolk Island",
                "code" => "NF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 159,
                "name" => "Northern Mariana Islands",
                "code" => "MP",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 160,
                "name" => "Norway",
                "code" => "NO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 161,
                "name" => "Oman",
                "code" => "OM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 162,
                "name" => "Pakistan",
                "code" => "PK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 163,
                "name" => "Palau",
                "code" => "PW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 164,
                "name" => "Panama",
                "code" => "PA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 165,
                "name" => "Papua New Guinea",
                "code" => "PG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 166,
                "name" => "Paraguay",
                "code" => "PY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 167,
                "name" => "Peru",
                "code" => "PE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 168,
                "name" => "Philippines",
                "code" => "PH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 169,
                "name" => "Pitcairn",
                "code" => "PN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 170,
                "name" => "Poland",
                "code" => "PL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 171,
                "name" => "Portugal",
                "code" => "PT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 172,
                "name" => "Puerto Rico",
                "code" => "PR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 173,
                "name" => "Qatar",
                "code" => "QA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 174,
                "name" => "Reunion",
                "code" => "RE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 175,
                "name" => "Romania",
                "code" => "RO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 176,
                "name" => "Russian Federation",
                "code" => "RU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 177,
                "name" => "Rwanda",
                "code" => "RW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 178,
                "name" => "Saint Kitts and Nevis",
                "code" => "KN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 179,
                "name" => "Saint Lucia",
                "code" => "LC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 180,
                "name" => "Saint Vincent and the Grenadines",
                "code" => "VC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 181,
                "name" => "Samoa",
                "code" => "WS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 182,
                "name" => "San Marino",
                "code" => "SM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 183,
                "name" => "Sao Tome and Principe",
                "code" => "ST",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 184,
                "name" => "Saudi Arabia",
                "code" => "SA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 185,
                "name" => "Senegal",
                "code" => "SN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 186,
                "name" => "Seychelles",
                "code" => "SC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 187,
                "name" => "Sierra Leone",
                "code" => "SL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 188,
                "name" => "Singapore",
                "code" => "SG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 189,
                "name" => "Slovak Republic",
                "code" => "SK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 190,
                "name" => "Slovenia",
                "code" => "SI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 191,
                "name" => "Solomon Islands",
                "code" => "SB",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 192,
                "name" => "Somalia",
                "code" => "SO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 193,
                "name" => "South Africa",
                "code" => "ZA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 194,
                "name" => "South Georgia &amp; South Sandwich Islands",
                "code" => "GS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 195,
                "name" => "Spain",
                "code" => "ES",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 196,
                "name" => "Sri Lanka",
                "code" => "LK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 197,
                "name" => "St. Helena",
                "code" => "SH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 198,
                "name" => "St. Pierre and Miquelon",
                "code" => "PM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 199,
                "name" => "Sudan",
                "code" => "SD",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 200,
                "name" => "Suriname",
                "code" => "SR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 201,
                "name" => "Svalbard and Jan Mayen Islands",
                "code" => "SJ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 202,
                "name" => "Swaziland",
                "code" => "SZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 203,
                "name" => "Sweden",
                "code" => "SE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 204,
                "name" => "Switzerland",
                "code" => "CH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 205,
                "name" => "Syrian Arab Republic",
                "code" => "SY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 207,
                "name" => "Tajikistan",
                "code" => "TJ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 208,
                "name" => "Tanzania, United Republic of",
                "code" => "TZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 209,
                "name" => "Thailand",
                "code" => "TH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 210,
                "name" => "Togo",
                "code" => "TG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 211,
                "name" => "Tokelau",
                "code" => "TK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 212,
                "name" => "Tonga",
                "code" => "TO",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 213,
                "name" => "Trinidad and Tobago",
                "code" => "TT",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 214,
                "name" => "Tunisia",
                "code" => "TN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 215,
                "name" => "Turkey",
                "code" => "TR",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 216,
                "name" => "Turkmenistan",
                "code" => "TM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 217,
                "name" => "Turks and Caicos Islands",
                "code" => "TC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 218,
                "name" => "Tuvalu",
                "code" => "TV",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 219,
                "name" => "Uganda",
                "code" => "UG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 220,
                "name" => "Ukraine",
                "code" => "UA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 221,
                "name" => "United Arab Emirates",
                "code" => "AE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 222,
                "name" => "United Kingdom",
                "code" => "GB",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 223,
                "name" => "United States",
                "code" => "US",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 224,
                "name" => "United States Minor Outlying Islands",
                "code" => "UM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 225,
                "name" => "Uruguay",
                "code" => "UY",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 226,
                "name" => "Uzbekistan",
                "code" => "UZ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 227,
                "name" => "Vanuatu",
                "code" => "VU",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 228,
                "name" => "Vatican City State (Holy See)",
                "code" => "VA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 229,
                "name" => "Venezuela",
                "code" => "VE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 230,
                "name" => "Viet Nam",
                "code" => "VN",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 231,
                "name" => "Virgin Islands (British)",
                "code" => "VG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 232,
                "name" => "Virgin Islands (U.S.)",
                "code" => "VI",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 233,
                "name" => "Wallis and Futuna Islands",
                "code" => "WF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 234,
                "name" => "Western Sahara",
                "code" => "EH",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 235,
                "name" => "Yemen",
                "code" => "YE",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 237,
                "name" => "Democratic Republic of Congo",
                "code" => "CD",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 238,
                "name" => "Zambia",
                "code" => "ZM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 239,
                "name" => "Zimbabwe",
                "code" => "ZW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 242,
                "name" => "Montenegro",
                "code" => "ME",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 243,
                "name" => "Serbia",
                "code" => "RS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 244,
                "name" => "Aaland Islands",
                "code" => "AX",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 245,
                "name" => "Bonaire, Sint Eustatius and Saba",
                "code" => "BQ",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 246,
                "name" => "Curacao",
                "code" => "CW",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 247,
                "name" => "Palestinian Territory, Occupied",
                "code" => "PS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 248,
                "name" => "South Sudan",
                "code" => "SS",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 249,
                "name" => "St. Barthelemy",
                "code" => "BL",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 250,
                "name" => "St. Martin (French part)",
                "code" => "MF",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 251,
                "name" => "Canary Islands",
                "code" => "IC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 252,
                "name" => "Ascension Island (British)",
                "code" => "AC",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 253,
                "name" => "Kosovo, Republic of",
                "code" => "XK",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 254,
                "name" => "Isle of Man",
                "code" => "IM",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 255,
                "name" => "Tristan da Cunha",
                "code" => "TA",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 256,
                "name" => "Guernsey",
                "code" => "GG",
                "sort_order" => 0,
                "status" => 1,
            ],
            [
                "id" => 257,
                "name" => "Jersey",
                "code" => "JE",
                "sort_order" => 0,
                "status" => 1,
            ]
        ];
    }
}
