<?php
/**
 * ProductsSeeder.php
 *
 * @copyright  2022 beikeshop.com - All Rights Reserved
 * @link       https://beikeshop.com
 * @author     Edward Yang <yangjin@guangda.work>
 * @created    2022-09-05 19:42:42
 * @modified   2022-09-05 19:42:42
 */

namespace Database\Seeders;

use Beike\Models\Product;
use Beike\Models\ProductRelation;
use Beike\Models\ProductSku;
use Illuminate\Database\Seeder;
use Beike\Models\ProductCategory;
use Beike\Models\ProductDescription;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 产品主表
        $products = $this->getProducts();
        if ($products) {
            Product::query()->truncate();
            foreach ($products as $item) {
                $item['images'] = json_decode($item['images'] ?? '');
                $item['variables'] = json_decode($item['variables'] ?? '');
                Product::query()->create($item);
            }
        }

        // 产品分类关联
        $categories = $this->getProductCategories();
        if ($categories) {
            ProductCategory::query()->truncate();
            foreach ($categories as $item) {
                ProductCategory::query()->create($item);
            }
        }

        // 产品描述
        $descriptions = $this->getProductDescriptions();
        if ($descriptions) {
            ProductDescription::query()->truncate();
            foreach ($descriptions as $item) {
                ProductDescription::query()->create($item);
            }
        }

        // 子商品SKU
        $skus = $this->getProductSkus();
        if ($skus) {
            ProductSku::query()->truncate();
            foreach ($skus as $item) {
                $item['created_at'] = now();
                $item['updated_at'] = now();
                $item['images'] = json_decode($item['images']);
                $item['variants'] = json_decode($item['variants']);
                ProductSku::query()->create($item);
            }
        }

        // 相关产品
        ProductRelation::query()->truncate();
        $items = $this->getProductRelations();
        ProductRelation::query()->insert(
            collect($items)->map(function ($item) {
                $item['created_at'] = now();
                $item['updated_at'] = now();
                return $item;
            })->toArray()
        );
    }


    private function getProducts(): array
    {
        return [
            [
                "id" => 1,
                "brand_id" => 10,
                "images" => "[\"catalog/demo/product/1.jpg\", \"catalog/demo/product/2.jpg\", \"catalog/demo/product/4.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 0,
                "active" => 1,
                "variables" => "[{\"name\": {\"en\": \"chima\", \"zh_cn\": \"尺码\"}, \"values\": [{\"name\": {\"en\": \"L\", \"zh_cn\": \"L\"}, \"image\": \"\"}, {\"name\": {\"en\": \"M\", \"zh_cn\": \"M\"}, \"image\": \"\"}], \"isImage\": false}, {\"name\": {\"en\": \"yanse\", \"zh_cn\": \"颜色\"}, \"values\": [{\"name\": {\"en\": \"黄色\", \"zh_cn\": \"黄色\"}, \"image\": \"\"}, {\"name\": {\"en\": \"绿色\", \"zh_cn\": \"绿色\"}, \"image\": \"\"}], \"isImage\": false}]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 2,
                "brand_id" => 11,
                "images" => "[\"catalog/demo/product/13.jpg\", \"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[{\"name\": {\"en\": \"Size\", \"zh_cn\": \"尺寸\"}, \"values\": [{\"name\": {\"en\": \"S\", \"zh_cn\": \"S\"}, \"image\": \"\"}, {\"name\": {\"en\": \"M\", \"zh_cn\": \"M\"}, \"image\": \"\"}, {\"name\": {\"en\": \"L\", \"zh_cn\": \"L\"}, \"image\": \"\"}], \"isImage\": false}, {\"name\": {\"en\": \"颜色\", \"zh_cn\": \"颜色\"}, \"values\": [{\"name\": {\"en\": \"Yellow\", \"zh_cn\": \"黄色\"}, \"image\": \"\"}, {\"name\": {\"en\": \"Blue\", \"zh_cn\": \"蓝色\"}, \"image\": \"\"}], \"isImage\": false}]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 3,
                "brand_id" => 4,
                "images" => "[\"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\", \"catalog/demo/product/17.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[{\"name\": {\"en\": \"Size\", \"zh_cn\": \"尺码\"}, \"values\": [{\"name\": {\"en\": \"S\", \"zh_cn\": \"S\"}, \"image\": \"\"}, {\"name\": {\"en\": \"M\", \"zh_cn\": \"M\"}, \"image\": \"\"}, {\"name\": {\"en\": \"L\", \"zh_cn\": \"L\"}, \"image\": \"\"}, {\"name\": {\"en\": \"XL\", \"zh_cn\": \"XL\"}, \"image\": \"\"}], \"isImage\": false}, {\"name\": {\"en\": \"Color\", \"zh_cn\": \"颜色\"}, \"values\": [{\"name\": {\"en\": \"Green\", \"zh_cn\": \"绿色\"}, \"image\": \"\"}, {\"name\": {\"en\": \"White\", \"zh_cn\": \"白色\"}, \"image\": \"\"}], \"isImage\": false}]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 4,
                "brand_id" => 7,
                "images" => "[\"catalog/demo/product/3.jpg\", \"catalog/demo/product/16.jpg\", \"catalog/demo/product/15.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[{\"name\": {\"en\": \"Size\", \"zh_cn\": \"尺码\"}, \"values\": [{\"name\": {\"en\": \"S\", \"zh_cn\": \"S\"}, \"image\": \"\"}, {\"name\": {\"en\": \"M\", \"zh_cn\": \"M\"}, \"image\": \"\"}, {\"name\": {\"en\": \"L\", \"zh_cn\": \"L\"}, \"image\": \"\"}, {\"name\": {\"en\": \"XL\", \"zh_cn\": \"XL\"}, \"image\": \"\"}], \"isImage\": false}, {\"name\": {\"en\": \"Color\", \"zh_cn\": \"颜色\"}, \"values\": [{\"name\": {\"en\": \"White\", \"zh_cn\": \"白色\"}, \"image\": \"\"}, {\"name\": {\"en\": \"Green\", \"zh_cn\": \"绿色\"}, \"image\": \"\"}], \"isImage\": false}]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 5,
                "brand_id" => 3,
                "images" => "[\"catalog/demo/product/4.jpg\", \"catalog/demo/product/15.jpg\", \"catalog/demo/product/16.jpg\", \"catalog/demo/product/17.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 6,
                "brand_id" => 2,
                "images" => "[\"catalog/demo/product/7.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 7,
                "brand_id" => 8,
                "images" => "[\"catalog/demo/product/5.jpg\", \"catalog/demo/product/16.jpg\", \"catalog/demo/product/3.jpg\", \"catalog/demo/product/9.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 8,
                "brand_id" => 5,
                "images" => "[\"catalog/demo/product/12.jpg\", \"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 9,
                "brand_id" => 2,
                "images" => "[\"catalog/demo/product/14.jpg\", \"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 10,
                "brand_id" => 1,
                "images" => "[\"catalog/demo/product/9.jpg\", \"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 11,
                "brand_id" => 2,
                "images" => "[\"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 12,
                "brand_id" => 2,
                "images" => "[\"catalog/demo/product/16.jpg\", \"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 13,
                "brand_id" => 8,
                "images" => "[\"catalog/demo/product/2.jpg\", \"catalog/demo/product/3.jpg\", \"catalog/demo/product/4.jpg\", \"catalog/demo/product/5.jpg\", \"catalog/demo/product/6.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 14,
                "brand_id" => 9,
                "images" => "[\"catalog/demo/product/6.jpg\", \"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 15,
                "brand_id" => 6,
                "images" => "[\"catalog/demo/product/15.jpg\", \"catalog/demo/product/10.jpg\", \"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 35,
                "brand_id" => 1,
                "images" => "[\"catalog/demo/product/18.jpg\", \"catalog/demo/product/2.jpg\", \"catalog/demo/product/3.jpg\", \"catalog/demo/product/4.jpg\", \"catalog/demo/product/5.jpg\", \"catalog/demo/product/6.jpg\", \"catalog/demo/product/7.jpg\", \"catalog/demo/product/9.jpg\", \"catalog/demo/product/xq_01.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ],
            [
                "id" => 39,
                "brand_id" => 4,
                "images" => "[\"catalog/demo/product/11.jpg\", \"catalog/demo/product/12.jpg\", \"catalog/demo/product/13.jpg\", \"catalog/demo/product/14.jpg\", \"catalog/demo/product/15.jpg\", \"catalog/demo/product/16.jpg\", \"catalog/demo/product/17.jpg\", \"catalog/demo/product/18.jpg\", \"catalog/demo/product/2.jpg\"]",
                "price" => 0,
                "video" => "",
                "position" => 1,
                "active" => 1,
                "variables" => "[{\"name\": {\"en\": \"color\", \"zh_cn\": \"颜色\"}, \"values\": [{\"name\": {\"en\": \"yellow\", \"zh_cn\": \"黄色\"}, \"image\": \"\"}, {\"name\": {\"en\": \"green\", \"zh_cn\": \"绿色\"}, \"image\": \"\"}], \"isImage\": true}, {\"name\": {\"en\": \"规格\", \"zh_cn\": \"规格\"}, \"values\": [{\"name\": {\"en\": \"450ML\", \"zh_cn\": \"450ML\"}, \"image\": \"\"}, {\"name\": {\"en\": \"500ml\", \"zh_cn\": \"500ml\"}, \"image\": \"\"}], \"isImage\": false}]",
                "tax_class_id" => 1,
                "sales" => 0,
                "deleted_at" => null
            ]
        ];
    }

    private function getProductCategories(): array
    {
        return [
            ["product_id" => 2, "category_id" => 100002,],
            ["product_id" => 2, "category_id" => 100003,],
            ["product_id" => 2, "category_id" => 100004,],
            ["product_id" => 2, "category_id" => 100005,],
            ["product_id" => 2, "category_id" => 100008,],
            ["product_id" => 2, "category_id" => 100007,],
            ["product_id" => 14, "category_id" => 100002,],
            ["product_id" => 14, "category_id" => 100003,],
            ["product_id" => 14, "category_id" => 100004,],
            ["product_id" => 14, "category_id" => 100005,],
            ["product_id" => 14, "category_id" => 100008,],
            ["product_id" => 14, "category_id" => 100007,],
            ["product_id" => 15, "category_id" => 100002,],
            ["product_id" => 15, "category_id" => 100003,],
            ["product_id" => 15, "category_id" => 100004,],
            ["product_id" => 15, "category_id" => 100005,],
            ["product_id" => 15, "category_id" => 100008,],
            ["product_id" => 15, "category_id" => 100007,],
            ["product_id" => 16, "category_id" => 100000,],
            ["product_id" => 16, "category_id" => 100002,],
            ["product_id" => 16, "category_id" => 100003,],
            ["product_id" => 16, "category_id" => 100004,],
            ["product_id" => 16, "category_id" => 100005,],
            ["product_id" => 16, "category_id" => 100008,],
            ["product_id" => 16, "category_id" => 100007,],
            ["product_id" => 16, "category_id" => 100009,],
            ["product_id" => 17, "category_id" => 100000,],
            ["product_id" => 17, "category_id" => 100002,],
            ["product_id" => 17, "category_id" => 100003,],
            ["product_id" => 17, "category_id" => 100004,],
            ["product_id" => 17, "category_id" => 100005,],
            ["product_id" => 17, "category_id" => 100008,],
            ["product_id" => 17, "category_id" => 100007,],
            ["product_id" => 17, "category_id" => 100009,],
            ["product_id" => 18, "category_id" => 100000,],
            ["product_id" => 18, "category_id" => 100002,],
            ["product_id" => 18, "category_id" => 100003,],
            ["product_id" => 18, "category_id" => 100004,],
            ["product_id" => 18, "category_id" => 100005,],
            ["product_id" => 18, "category_id" => 100008,],
            ["product_id" => 18, "category_id" => 100007,],
            ["product_id" => 18, "category_id" => 100009,],
            ["product_id" => 19, "category_id" => 100000,],
            ["product_id" => 19, "category_id" => 100002,],
            ["product_id" => 19, "category_id" => 100003,],
            ["product_id" => 19, "category_id" => 100004,],
            ["product_id" => 19, "category_id" => 100005,],
            ["product_id" => 19, "category_id" => 100008,],
            ["product_id" => 19, "category_id" => 100007,],
            ["product_id" => 19, "category_id" => 100009,],
            ["product_id" => 20, "category_id" => 100000,],
            ["product_id" => 20, "category_id" => 100002,],
            ["product_id" => 20, "category_id" => 100003,],
            ["product_id" => 20, "category_id" => 100004,],
            ["product_id" => 20, "category_id" => 100005,],
            ["product_id" => 20, "category_id" => 100008,],
            ["product_id" => 20, "category_id" => 100007,],
            ["product_id" => 20, "category_id" => 100009,],
            ["product_id" => 1, "category_id" => 100015,],
            ["product_id" => 2, "category_id" => 100013,],
            ["product_id" => 2, "category_id" => 100010,],
            ["product_id" => 2, "category_id" => 100011,],
            ["product_id" => 2, "category_id" => 100012,],
            ["product_id" => 2, "category_id" => 100014,],
            ["product_id" => 2, "category_id" => 100015,],
            ["product_id" => 2, "category_id" => 100018,],
            ["product_id" => 31, "category_id" => 100011,],
            ["product_id" => 32, "category_id" => 100008,],
            ["product_id" => 32, "category_id" => 100011,],
            ["product_id" => 32, "category_id" => 100012,],
            ["product_id" => 32, "category_id" => 100014,],
            ["product_id" => 34, "category_id" => 100013,],
            ["product_id" => 35, "category_id" => 100011,],
            ["product_id" => 35, "category_id" => 100012,],
            ["product_id" => 39, "category_id" => 100013,],
            ["product_id" => 39, "category_id" => 100002,],
            ["product_id" => 39, "category_id" => 100010,],
            ["product_id" => 39, "category_id" => 100003,],
            ["product_id" => 39, "category_id" => 100004,],
            ["product_id" => 39, "category_id" => 100005,],
            ["product_id" => 39, "category_id" => 100008,],
            ["product_id" => 39, "category_id" => 100011,],
            ["product_id" => 39, "category_id" => 100012,],
            ["product_id" => 39, "category_id" => 100014,],
            ["product_id" => 39, "category_id" => 100015,],
            ["product_id" => 2, "category_id" => 100016,],
            ["product_id" => 2, "category_id" => 100006,],
            ["product_id" => 3, "category_id" => 100012,],
            ["product_id" => 3, "category_id" => 100018,],
            ["product_id" => 3, "category_id" => 100017,],
            ["product_id" => 3, "category_id" => 100003,],
            ["product_id" => 3, "category_id" => 100005,],
            ["product_id" => 3, "category_id" => 100007,],
            ["product_id" => 3, "category_id" => 100002,],
            ["product_id" => 3, "category_id" => 100004,],
            ["product_id" => 3, "category_id" => 100010,],
            ["product_id" => 3, "category_id" => 100013,],
            ["product_id" => 3, "category_id" => 100015,],
            ["product_id" => 3, "category_id" => 100014,],
            ["product_id" => 3, "category_id" => 100016,],
            ["product_id" => 3, "category_id" => 100011,],
            ["product_id" => 3, "category_id" => 100006,],
            ["product_id" => 3, "category_id" => 100008,],
            ["product_id" => 4, "category_id" => 100012,],
            ["product_id" => 4, "category_id" => 100018,],
            ["product_id" => 4, "category_id" => 100017,],
            ["product_id" => 4, "category_id" => 100003,],
            ["product_id" => 4, "category_id" => 100005,],
            ["product_id" => 4, "category_id" => 100007,],
            ["product_id" => 4, "category_id" => 100002,],
            ["product_id" => 4, "category_id" => 100004,],
            ["product_id" => 4, "category_id" => 100010,],
            ["product_id" => 4, "category_id" => 100013,],
            ["product_id" => 4, "category_id" => 100015,],
            ["product_id" => 4, "category_id" => 100014,],
            ["product_id" => 4, "category_id" => 100016,],
            ["product_id" => 4, "category_id" => 100011,],
            ["product_id" => 4, "category_id" => 100006,],
            ["product_id" => 4, "category_id" => 100008,],
            ["product_id" => 6, "category_id" => 100012,],
            ["product_id" => 6, "category_id" => 100018,],
            ["product_id" => 6, "category_id" => 100017,],
            ["product_id" => 6, "category_id" => 100003,],
            ["product_id" => 6, "category_id" => 100005,],
            ["product_id" => 6, "category_id" => 100007,],
            ["product_id" => 6, "category_id" => 100002,],
            ["product_id" => 6, "category_id" => 100004,],
            ["product_id" => 6, "category_id" => 100010,],
            ["product_id" => 6, "category_id" => 100013,],
            ["product_id" => 6, "category_id" => 100015,],
            ["product_id" => 6, "category_id" => 100014,],
            ["product_id" => 6, "category_id" => 100016,],
            ["product_id" => 6, "category_id" => 100011,],
            ["product_id" => 6, "category_id" => 100006,],
            ["product_id" => 1, "category_id" => 100012,],
            ["product_id" => 1, "category_id" => 100018,],
            ["product_id" => 1, "category_id" => 100017,],
            ["product_id" => 1, "category_id" => 100003,],
            ["product_id" => 1, "category_id" => 100005,],
            ["product_id" => 1, "category_id" => 100007,],
            ["product_id" => 1, "category_id" => 100002,],
            ["product_id" => 1, "category_id" => 100004,],
            ["product_id" => 1, "category_id" => 100010,],
            ["product_id" => 1, "category_id" => 100013,],
            ["product_id" => 1, "category_id" => 100014,],
            ["product_id" => 1, "category_id" => 100016,],
            ["product_id" => 1, "category_id" => 100011,],
            ["product_id" => 1, "category_id" => 100006,],
            ["product_id" => 1, "category_id" => 100008,],
            ["product_id" => 39, "category_id" => 100018,],
            ["product_id" => 39, "category_id" => 100017,],
            ["product_id" => 39, "category_id" => 100007,],
            ["product_id" => 39, "category_id" => 100016,],
            ["product_id" => 35, "category_id" => 100018,],
            ["product_id" => 35, "category_id" => 100017,],
            ["product_id" => 35, "category_id" => 100003,],
            ["product_id" => 35, "category_id" => 100005,],
            ["product_id" => 35, "category_id" => 100007,],
            ["product_id" => 35, "category_id" => 100002,],
            ["product_id" => 35, "category_id" => 100004,],
            ["product_id" => 35, "category_id" => 100010,],
            ["product_id" => 35, "category_id" => 100013,],
            ["product_id" => 35, "category_id" => 100015,],
            ["product_id" => 35, "category_id" => 100014,],
            ["product_id" => 35, "category_id" => 100016,],
            ["product_id" => 35, "category_id" => 100006,],
            ["product_id" => 35, "category_id" => 100008,],
            ["product_id" => 15, "category_id" => 100012,],
            ["product_id" => 15, "category_id" => 100018,],
            ["product_id" => 15, "category_id" => 100017,],
            ["product_id" => 15, "category_id" => 100010,],
            ["product_id" => 15, "category_id" => 100013,],
            ["product_id" => 15, "category_id" => 100015,],
            ["product_id" => 15, "category_id" => 100014,],
            ["product_id" => 15, "category_id" => 100016,],
            ["product_id" => 15, "category_id" => 100011,],
            ["product_id" => 15, "category_id" => 100006,],
            ["product_id" => 14, "category_id" => 100012,],
            ["product_id" => 14, "category_id" => 100018,],
            ["product_id" => 14, "category_id" => 100017,],
            ["product_id" => 14, "category_id" => 100010,],
            ["product_id" => 14, "category_id" => 100013,],
            ["product_id" => 14, "category_id" => 100015,],
            ["product_id" => 14, "category_id" => 100014,],
            ["product_id" => 14, "category_id" => 100016,],
            ["product_id" => 14, "category_id" => 100011,],
            ["product_id" => 14, "category_id" => 100006,],
            ["product_id" => 13, "category_id" => 100012,],
            ["product_id" => 13, "category_id" => 100018,],
            ["product_id" => 13, "category_id" => 100017,],
            ["product_id" => 13, "category_id" => 100003,],
            ["product_id" => 13, "category_id" => 100005,],
            ["product_id" => 13, "category_id" => 100007,],
            ["product_id" => 13, "category_id" => 100002,],
            ["product_id" => 13, "category_id" => 100004,],
            ["product_id" => 13, "category_id" => 100010,],
            ["product_id" => 13, "category_id" => 100013,],
            ["product_id" => 13, "category_id" => 100015,],
            ["product_id" => 13, "category_id" => 100014,],
            ["product_id" => 13, "category_id" => 100016,],
            ["product_id" => 13, "category_id" => 100011,],
            ["product_id" => 13, "category_id" => 100006,],
            ["product_id" => 13, "category_id" => 100008,],
            ["product_id" => 12, "category_id" => 100012,],
            ["product_id" => 12, "category_id" => 100018,],
            ["product_id" => 12, "category_id" => 100017,],
            ["product_id" => 12, "category_id" => 100003,],
            ["product_id" => 12, "category_id" => 100005,],
            ["product_id" => 12, "category_id" => 100007,],
            ["product_id" => 12, "category_id" => 100002,],
            ["product_id" => 12, "category_id" => 100004,],
            ["product_id" => 12, "category_id" => 100010,],
            ["product_id" => 12, "category_id" => 100013,],
            ["product_id" => 12, "category_id" => 100015,],
            ["product_id" => 12, "category_id" => 100014,],
            ["product_id" => 12, "category_id" => 100016,],
            ["product_id" => 12, "category_id" => 100011,],
            ["product_id" => 12, "category_id" => 100006,],
            ["product_id" => 12, "category_id" => 100008,],
            ["product_id" => 11, "category_id" => 100012,],
            ["product_id" => 11, "category_id" => 100018,],
            ["product_id" => 11, "category_id" => 100017,],
            ["product_id" => 11, "category_id" => 100003,],
            ["product_id" => 11, "category_id" => 100005,],
            ["product_id" => 11, "category_id" => 100007,],
            ["product_id" => 11, "category_id" => 100002,],
            ["product_id" => 11, "category_id" => 100004,],
            ["product_id" => 11, "category_id" => 100010,],
            ["product_id" => 11, "category_id" => 100013,],
            ["product_id" => 11, "category_id" => 100015,],
            ["product_id" => 11, "category_id" => 100014,],
            ["product_id" => 11, "category_id" => 100016,],
            ["product_id" => 11, "category_id" => 100011,],
            ["product_id" => 11, "category_id" => 100006,],
            ["product_id" => 11, "category_id" => 100008,],
            ["product_id" => 10, "category_id" => 100012,],
            ["product_id" => 10, "category_id" => 100018,],
            ["product_id" => 10, "category_id" => 100017,],
            ["product_id" => 10, "category_id" => 100003,],
            ["product_id" => 10, "category_id" => 100005,],
            ["product_id" => 10, "category_id" => 100007,],
            ["product_id" => 10, "category_id" => 100002,],
            ["product_id" => 10, "category_id" => 100004,],
            ["product_id" => 10, "category_id" => 100010,],
            ["product_id" => 10, "category_id" => 100013,],
            ["product_id" => 10, "category_id" => 100015,],
            ["product_id" => 10, "category_id" => 100014,],
            ["product_id" => 10, "category_id" => 100016,],
            ["product_id" => 10, "category_id" => 100011,],
            ["product_id" => 10, "category_id" => 100006,],
            ["product_id" => 10, "category_id" => 100008,],
            ["product_id" => 9, "category_id" => 100012,],
            ["product_id" => 9, "category_id" => 100018,],
            ["product_id" => 9, "category_id" => 100017,],
            ["product_id" => 9, "category_id" => 100003,],
            ["product_id" => 9, "category_id" => 100005,],
            ["product_id" => 9, "category_id" => 100007,],
            ["product_id" => 9, "category_id" => 100002,],
            ["product_id" => 9, "category_id" => 100004,],
            ["product_id" => 9, "category_id" => 100010,],
            ["product_id" => 9, "category_id" => 100013,],
            ["product_id" => 9, "category_id" => 100015,],
            ["product_id" => 9, "category_id" => 100014,],
            ["product_id" => 9, "category_id" => 100016,],
            ["product_id" => 9, "category_id" => 100011,],
            ["product_id" => 9, "category_id" => 100006,],
            ["product_id" => 9, "category_id" => 100008,],
            ["product_id" => 8, "category_id" => 100012,],
            ["product_id" => 8, "category_id" => 100018,],
            ["product_id" => 8, "category_id" => 100017,],
            ["product_id" => 8, "category_id" => 100003,],
            ["product_id" => 8, "category_id" => 100005,],
            ["product_id" => 8, "category_id" => 100007,],
            ["product_id" => 8, "category_id" => 100002,],
            ["product_id" => 8, "category_id" => 100004,],
            ["product_id" => 8, "category_id" => 100010,],
            ["product_id" => 8, "category_id" => 100013,],
            ["product_id" => 8, "category_id" => 100015,],
            ["product_id" => 8, "category_id" => 100014,],
            ["product_id" => 8, "category_id" => 100016,],
            ["product_id" => 8, "category_id" => 100011,],
            ["product_id" => 8, "category_id" => 100006,],
            ["product_id" => 8, "category_id" => 100008,],
            ["product_id" => 7, "category_id" => 100012,],
            ["product_id" => 7, "category_id" => 100018,],
            ["product_id" => 7, "category_id" => 100017,],
            ["product_id" => 7, "category_id" => 100003,],
            ["product_id" => 7, "category_id" => 100005,],
            ["product_id" => 7, "category_id" => 100007,],
            ["product_id" => 7, "category_id" => 100002,],
            ["product_id" => 7, "category_id" => 100004,],
            ["product_id" => 7, "category_id" => 100010,],
            ["product_id" => 7, "category_id" => 100013,],
            ["product_id" => 7, "category_id" => 100015,],
            ["product_id" => 7, "category_id" => 100014,],
            ["product_id" => 7, "category_id" => 100016,],
            ["product_id" => 7, "category_id" => 100011,],
            ["product_id" => 7, "category_id" => 100006,],
            ["product_id" => 7, "category_id" => 100008,],
            ["product_id" => 6, "category_id" => 100008,],
            ["product_id" => 5, "category_id" => 100012,],
            ["product_id" => 5, "category_id" => 100018,],
            ["product_id" => 5, "category_id" => 100017,],
            ["product_id" => 5, "category_id" => 100003,],
            ["product_id" => 5, "category_id" => 100005,],
            ["product_id" => 5, "category_id" => 100007,],
            ["product_id" => 5, "category_id" => 100002,],
            ["product_id" => 5, "category_id" => 100004,],
            ["product_id" => 5, "category_id" => 100010,],
            ["product_id" => 5, "category_id" => 100013,],
            ["product_id" => 5, "category_id" => 100015,],
            ["product_id" => 5, "category_id" => 100014,],
            ["product_id" => 5, "category_id" => 100016,],
            ["product_id" => 5, "category_id" => 100011,],
            ["product_id" => 5, "category_id" => 100006,],
            ["product_id" => 5, "category_id" => 100008,],
        ];
    }

    private function getProductDescriptions(): array
    {
        return [
            [
                "id" => 19,
                "product_id" => 16,
                "locale" => "zh_cn",
                "name" => "ddasda",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 20,
                "product_id" => 16,
                "locale" => "en",
                "name" => "3213123",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 23,
                "product_id" => 17,
                "locale" => "zh_cn",
                "name" => "ddasda",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 24,
                "product_id" => 17,
                "locale" => "en",
                "name" => "3213123",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 27,
                "product_id" => 18,
                "locale" => "zh_cn",
                "name" => "ddasda",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 28,
                "product_id" => 18,
                "locale" => "en",
                "name" => "3213123",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 31,
                "product_id" => 19,
                "locale" => "zh_cn",
                "name" => "ddasda",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 32,
                "product_id" => 19,
                "locale" => "en",
                "name" => "3213123",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 35,
                "product_id" => 20,
                "locale" => "zh_cn",
                "name" => "ddasda",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 36,
                "product_id" => 20,
                "locale" => "en",
                "name" => "3213123",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 65,
                "product_id" => 2,
                "locale" => "zh_cn",
                "name" => "中长款牛仔半身裙女春夏季2021新款薄款高腰开叉包臀长裙A字裙子",
                "content" => "fdsfsd",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 66,
                "product_id" => 2,
                "locale" => "en",
                "name" => "Mid-length denim skirt woman Spring/summer 2021 new thin high waisted slit hip wrap skirt A-line skirt",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 67,
                "product_id" => 3,
                "locale" => "zh_cn",
                "name" => "双肩包书包男女笔记本电脑包时尚潮流旅行背包",
                "content" => "测试下商品详情",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 68,
                "product_id" => 3,
                "locale" => "en",
                "name" => "Backpack Men and women laptop bag fashion trend travel backpack",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 75,
                "product_id" => 7,
                "locale" => "zh_cn",
                "name" => "轻便跑鞋女夏新款跑步运动鞋减震软底网面透气休闲运动鞋女鞋",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 76,
                "product_id" => 7,
                "locale" => "en",
                "name" => "Lightweight running shoes female summer new running shoes shock absorption soft bottom",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 79,
                "product_id" => 9,
                "locale" => "zh_cn",
                "name" => "春夏新品暗黑系甜辣风吊带裙欧根纱蓬蓬裙冷淡法式连衣裙女",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 80,
                "product_id" => 9,
                "locale" => "en",
                "name" => "Spring and summer NEW dark department of sweet hot wind sling skirt organza skirt cold French dress female",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 83,
                "product_id" => 11,
                "locale" => "zh_cn",
                "name" => "夏季新款polo领连衣裙女学院风减龄不规则下摆长裙子",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 84,
                "product_id" => 11,
                "locale" => "en",
                "name" => "New polo collar dress for summer women's college style aging irregular hem long skirt",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 85,
                "product_id" => 12,
                "locale" => "zh_cn",
                "name" => "凉鞋女款夏季2022年新款坡跟女鞋夏款松糕鞋高跟鞋子爆款女士",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 86,
                "product_id" => 12,
                "locale" => "en",
                "name" => "Sandal women's Summer 2022 new wedge women's shoes summer style",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 87,
                "product_id" => 13,
                "locale" => "zh_cn",
                "name" => "休闲polo衬衫连衣裙大码女装高级感夏2022新款小个子御姐",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 88,
                "product_id" => 13,
                "locale" => "en",
                "name" => "Casual Polo shirt dress large size women's senior sense summer 2022 new small royal sister",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 89,
                "product_id" => 14,
                "locale" => "zh_cn",
                "name" => "夏季套装短袖T恤男装一套搭配帅气潮情侣男生半袖上衣服",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 90,
                "product_id" => 14,
                "locale" => "en",
                "name" => "Summer suit short sleeve T-shirt men's suit with handsome fashionable couple boys half sleeve clothes",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 101,
                "product_id" => 28,
                "locale" => "zh_cn",
                "name" => "321",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 102,
                "product_id" => 28,
                "locale" => "en",
                "name" => "3123",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 105,
                "product_id" => 30,
                "locale" => "zh_cn",
                "name" => "1",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 106,
                "product_id" => 30,
                "locale" => "en",
                "name" => "1",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 115,
                "product_id" => 31,
                "locale" => "zh_cn",
                "name" => "中国乔丹",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 116,
                "product_id" => 31,
                "locale" => "en",
                "name" => "中国乔丹",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 125,
                "product_id" => 34,
                "locale" => "zh_cn",
                "name" => "芦荟胶",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 126,
                "product_id" => 34,
                "locale" => "en",
                "name" => "English芦荟胶",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 149,
                "product_id" => 32,
                "locale" => "zh_cn",
                "name" => "虎牌保温杯",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 150,
                "product_id" => 32,
                "locale" => "en",
                "name" => "虎牌保温杯",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 203,
                "product_id" => 6,
                "locale" => "zh_cn",
                "name" => "冰丝褶皱垂感圆领长袖T恤男宽松薄款高级感v领男装上衣",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 204,
                "product_id" => 6,
                "locale" => "en",
                "name" => "Ice silk drape feel round neck long sleeve T-shirt men loose thin senior sense",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 291,
                "product_id" => 39,
                "locale" => "zh_cn",
                "name" => "夏季新款女装法式气质洋气高级感温柔风吊带仙女连衣裙",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 292,
                "product_id" => 39,
                "locale" => "en",
                "name" => "Summer new women's French temperament Western style high-end gentle wind sling fairy dress",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
                "created_at" => "2022-08-26 09:20:14",
                "updated_at" => "2022-08-26 09:20:14"
            ],
            [
                "id" => 293,
                "product_id" => 35,
                "locale" => "zh_cn",
                "name" => "气质通勤高街蛋青色挺括烟管裤9分裤套装下装22秋女",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 294,
                "product_id" => 35,
                "locale" => "en",
                "name" => "Temperament commuter high street egg cyan stiff cigarette pants 9 points pants suit bottoms 22 autumn women",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 295,
                "product_id" => 4,
                "locale" => "zh_cn",
                "name" => "男子 休闲鞋 TANJUN 天君 休闲鞋 运动鞋 812654",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 296,
                "product_id" => 4,
                "locale" => "en",
                "name" => "Men's casual shoes TANJUN Tianjun casual shoes sneakers 812654",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 297,
                "product_id" => 8,
                "locale" => "zh_cn",
                "name" => "夏季新款模糊数码直喷短袖上衣男装情侣纯棉t恤ins潮",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 298,
                "product_id" => 8,
                "locale" => "en",
                "name" => "Summer new fuzzy digital direct spray short sleeve top men's pair of cotton T-shirt Instagram trend",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 299,
                "product_id" => 5,
                "locale" => "zh_cn",
                "name" => "高级感男装夏季潮牌美式复古短袖t恤男士重磅纯棉宽松半袖男体恤",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 300,
                "product_id" => 5,
                "locale" => "en",
                "name" => "High sense men's summer fashion brand American vintage short sleeve T-shirt men",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 301,
                "product_id" => 10,
                "locale" => "zh_cn",
                "name" => "法式小众设计高级感连衣裙2022年新款收腰显瘦中长款裙子女夏",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 302,
                "product_id" => 10,
                "locale" => "en",
                "name" => "French niche design haute couture dress 2022 new waist",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 303,
                "product_id" => 1,
                "locale" => "zh_cn",
                "name" => "欧洲站夏季新款时尚休闲短裤热裤女裤运动家具纯棉韩版宽松百搭裤",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 304,
                "product_id" => 1,
                "locale" => "en",
                "name" => "European station summer new FASHION casual shorts hot pants female pants sports furniture pure cotton Korean version loose pants",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 305,
                "product_id" => 15,
                "locale" => "zh_cn",
                "name" => "男鞋2022夏季透气冲孔时尚休闲板鞋压花耐磨小白鞋男",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
            [
                "id" => 306,
                "product_id" => 15,
                "locale" => "en",
                "name" => "Male shoes 2022 summer breathable punching fashion casual shoes embossed wear resistant small white shoes male",
                "content" => "<p><img class=\"img-fluid\" src=\"/catalog/demo/product/xq_01.jpg\" /></p>",
                "meta_title" => "",
                "meta_description" => "",
                "meta_keywords" => "",
            ],
        ];
    }

    private function getProductSkus(): array
    {
        return [
            [
                "id" => 273,
                "product_id" => 5,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model273",
                "sku" => "sku273",
                "price" => 999,
                "origin_price" => 2222,
                "cost_price" => 222,
                "quantity" => 42131,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 274,
                "product_id" => 6,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model274",
                "sku" => "sku274",
                "price" => 423,
                "origin_price" => 44232,
                "cost_price" => 3,
                "quantity" => 123123,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 275,
                "product_id" => 7,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model275",
                "sku" => "sku275",
                "price" => 99,
                "origin_price" => 299,
                "cost_price" => 299,
                "quantity" => 3333,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 276,
                "product_id" => 8,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model276",
                "sku" => "sku276",
                "price" => 99,
                "origin_price" => 333,
                "cost_price" => 222,
                "quantity" => 2222,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 277,
                "product_id" => 9,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model277",
                "sku" => "sku277",
                "price" => 299,
                "origin_price" => 999,
                "cost_price" => 99,
                "quantity" => 99,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 278,
                "product_id" => 10,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model278",
                "sku" => "sku278",
                "price" => 169,
                "origin_price" => 334,
                "cost_price" => 55,
                "quantity" => 33,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 279,
                "product_id" => 11,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model279",
                "sku" => "sku279",
                "price" => 98,
                "origin_price" => 234,
                "cost_price" => 223,
                "quantity" => 2223,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 280,
                "product_id" => 12,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model280",
                "sku" => "sku280",
                "price" => 79,
                "origin_price" => 222,
                "cost_price" => 333,
                "quantity" => 2222,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 281,
                "product_id" => 13,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model281",
                "sku" => "sku281",
                "price" => 199,
                "origin_price" => 333,
                "cost_price" => 333,
                "quantity" => 3445,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 282,
                "product_id" => 14,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model282",
                "sku" => "sku282",
                "price" => 299,
                "origin_price" => 433,
                "cost_price" => 234,
                "quantity" => 423,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 283,
                "product_id" => 15,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model283",
                "sku" => "sku283",
                "price" => 324,
                "origin_price" => 35,
                "cost_price" => 43,
                "quantity" => 546,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 284,
                "product_id" => 35,
                "variants" => "\"\"",
                "position" => 0,
                "images" => null,
                "model" => "model284",
                "sku" => "sku284",
                "price" => 100.99,
                "origin_price" => 50.99,
                "cost_price" => 30.99,
                "quantity" => 999,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 285,
                "product_id" => 39,
                "variants" => "[\"0\", \"0\"]",
                "position" => 0,
                "images" => "[\"catalog/demo/product/12.jpg\"]",
                "model" => "model285",
                "sku" => "sku285",
                "price" => 100,
                "origin_price" => 3534,
                "cost_price" => 3453,
                "quantity" => 999,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 286,
                "product_id" => 39,
                "variants" => "[\"0\", \"1\"]",
                "position" => 1,
                "images" => "[\"catalog/demo/product/15.jpg\"]",
                "model" => "model286",
                "sku" => "sku286",
                "price" => 56,
                "origin_price" => 353,
                "cost_price" => 454,
                "quantity" => 454,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 287,
                "product_id" => 39,
                "variants" => "[\"1\", \"0\"]",
                "position" => 2,
                "images" => "[\"catalog/demo/product/18.jpg\"]",
                "model" => "model287",
                "sku" => "sku287",
                "price" => 454,
                "origin_price" => 353,
                "cost_price" => 345,
                "quantity" => 45,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 288,
                "product_id" => 39,
                "variants" => "[\"1\", \"1\"]",
                "position" => 3,
                "images" => "[\"catalog/demo/product/4.jpg\"]",
                "model" => "model288",
                "sku" => "sku288",
                "price" => 3534,
                "origin_price" => 353,
                "cost_price" => 4545,
                "quantity" => 45,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 289,
                "product_id" => 1,
                "variants" => "[\"0\", \"0\"]",
                "position" => 0,
                "images" => "[\"catalog/demo/product/17.jpg\"]",
                "model" => "model289",
                "sku" => "sku289",
                "price" => 88.3,
                "origin_price" => 2312,
                "cost_price" => 2312,
                "quantity" => 2222,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 290,
                "product_id" => 1,
                "variants" => "[\"0\", \"1\"]",
                "position" => 1,
                "images" => "[\"catalog/demo/product/10.jpg\"]",
                "model" => "model290",
                "sku" => "sku290",
                "price" => 448.3,
                "origin_price" => 2312,
                "cost_price" => 2312,
                "quantity" => 0,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 291,
                "product_id" => 1,
                "variants" => "[\"1\", \"0\"]",
                "position" => 2,
                "images" => "[\"catalog/demo/product/17.jpg\"]",
                "model" => "model291",
                "sku" => "sku291",
                "price" => 18.3,
                "origin_price" => 2312,
                "cost_price" => 2312,
                "quantity" => 22,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 292,
                "product_id" => 1,
                "variants" => "[\"1\", \"1\"]",
                "position" => 3,
                "images" => "[\"catalog/demo/product/10.jpg\"]",
                "model" => "model292",
                "sku" => "sku292",
                "price" => 78.3,
                "origin_price" => 2312,
                "cost_price" => 2312,
                "quantity" => 3333,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 299,
                "product_id" => 2,
                "variants" => "[\"0\", \"0\"]",
                "position" => 0,
                "images" => "[\"catalog/demo/product/13.jpg\"]",
                "model" => "model299",
                "sku" => "sku299",
                "price" => 324,
                "origin_price" => 213,
                "cost_price" => 312,
                "quantity" => 546,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 300,
                "product_id" => 2,
                "variants" => "[\"0\", \"1\"]",
                "position" => 1,
                "images" => "[\"catalog/demo/product/2.jpg\"]",
                "model" => "model300",
                "sku" => "sku300",
                "price" => 231,
                "origin_price" => 213,
                "cost_price" => 31,
                "quantity" => 2312,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 301,
                "product_id" => 2,
                "variants" => "[\"1\", \"0\"]",
                "position" => 2,
                "images" => null,
                "model" => "model301",
                "sku" => "sku301",
                "price" => 123,
                "origin_price" => 3123,
                "cost_price" => 23,
                "quantity" => 432,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 302,
                "product_id" => 2,
                "variants" => "[\"1\", \"1\"]",
                "position" => 3,
                "images" => null,
                "model" => "model302",
                "sku" => "sku302",
                "price" => 542,
                "origin_price" => 12321,
                "cost_price" => 123,
                "quantity" => 555,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 303,
                "product_id" => 2,
                "variants" => "[\"2\", \"0\"]",
                "position" => 4,
                "images" => null,
                "model" => "model303",
                "sku" => "sku303",
                "price" => 671,
                "origin_price" => 213,
                "cost_price" => 123,
                "quantity" => 12,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 304,
                "product_id" => 2,
                "variants" => "[\"2\", \"1\"]",
                "position" => 5,
                "images" => null,
                "model" => "model304",
                "sku" => "sku304",
                "price" => 231,
                "origin_price" => 12,
                "cost_price" => 213123,
                "quantity" => 31231,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 305,
                "product_id" => 3,
                "variants" => "[\"0\", \"0\"]",
                "position" => 0,
                "images" => "[\"catalog/demo/product/11.jpg\"]",
                "model" => "model305",
                "sku" => "sku305",
                "price" => 299,
                "origin_price" => 312312,
                "cost_price" => 311,
                "quantity" => 444,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 306,
                "product_id" => 3,
                "variants" => "[\"0\", \"1\"]",
                "position" => 1,
                "images" => "[\"catalog/demo/product/12.jpg\"]",
                "model" => "model306",
                "sku" => "sku306",
                "price" => 123,
                "origin_price" => 321,
                "cost_price" => 451,
                "quantity" => 312,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 307,
                "product_id" => 3,
                "variants" => "[\"1\", \"0\"]",
                "position" => 2,
                "images" => "[\"catalog/demo/product/11.jpg\"]",
                "model" => "model307",
                "sku" => "sku307",
                "price" => 123,
                "origin_price" => 312,
                "cost_price" => 6423,
                "quantity" => 312,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 308,
                "product_id" => 3,
                "variants" => "[\"1\", \"1\"]",
                "position" => 3,
                "images" => "[\"catalog/demo/product/12.jpg\"]",
                "model" => "model308",
                "sku" => "sku308",
                "price" => 775,
                "origin_price" => 3,
                "cost_price" => 123,
                "quantity" => 0,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 309,
                "product_id" => 3,
                "variants" => "[\"2\", \"0\"]",
                "position" => 4,
                "images" => "[\"catalog/demo/product/11.jpg\"]",
                "model" => "model309",
                "sku" => "sku309",
                "price" => 313,
                "origin_price" => 32,
                "cost_price" => 14423,
                "quantity" => 333,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 310,
                "product_id" => 3,
                "variants" => "[\"2\", \"1\"]",
                "position" => 5,
                "images" => "[\"catalog/demo/product/12.jpg\"]",
                "model" => "model310",
                "sku" => "sku310",
                "price" => 2349,
                "origin_price" => 435,
                "cost_price" => 434,
                "quantity" => 111,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 311,
                "product_id" => 3,
                "variants" => "[\"3\", \"0\"]",
                "position" => 6,
                "images" => "[\"catalog/demo/product/11.jpg\"]",
                "model" => "model311",
                "sku" => "sku311",
                "price" => 2349,
                "origin_price" => 4678,
                "cost_price" => 654,
                "quantity" => 0,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 312,
                "product_id" => 3,
                "variants" => "[\"3\", \"1\"]",
                "position" => 7,
                "images" => "[\"catalog/demo/product/12.jpg\"]",
                "model" => "model312",
                "sku" => "sku312",
                "price" => 1299,
                "origin_price" => 6578,
                "cost_price" => 123,
                "quantity" => 11,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 313,
                "product_id" => 4,
                "variants" => "[\"0\", \"0\"]",
                "position" => 0,
                "images" => null,
                "model" => "model313",
                "sku" => "sku313",
                "price" => 99,
                "origin_price" => 123,
                "cost_price" => 312,
                "quantity" => 333,
                "is_default" => 1,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 314,
                "product_id" => 4,
                "variants" => "[\"0\", \"1\"]",
                "position" => 1,
                "images" => null,
                "model" => "model314",
                "sku" => "sku314",
                "price" => 23,
                "origin_price" => 33,
                "cost_price" => 312,
                "quantity" => 123,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 315,
                "product_id" => 4,
                "variants" => "[\"1\", \"0\"]",
                "position" => 2,
                "images" => null,
                "model" => "model315",
                "sku" => "sku315",
                "price" => 34,
                "origin_price" => 123,
                "cost_price" => 3,
                "quantity" => 33,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 316,
                "product_id" => 4,
                "variants" => "[\"1\", \"1\"]",
                "position" => 3,
                "images" => null,
                "model" => "model316",
                "sku" => "sku316",
                "price" => 55,
                "origin_price" => 13,
                "cost_price" => 32112,
                "quantity" => 3312,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 317,
                "product_id" => 4,
                "variants" => "[\"2\", \"0\"]",
                "position" => 4,
                "images" => null,
                "model" => "model317",
                "sku" => "sku317",
                "price" => 66,
                "origin_price" => 2312,
                "cost_price" => 32,
                "quantity" => 3,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 318,
                "product_id" => 4,
                "variants" => "[\"2\", \"1\"]",
                "position" => 5,
                "images" => null,
                "model" => "model318",
                "sku" => "sku318",
                "price" => 77,
                "origin_price" => 13,
                "cost_price" => 123,
                "quantity" => 3312,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 319,
                "product_id" => 4,
                "variants" => "[\"3\", \"0\"]",
                "position" => 6,
                "images" => null,
                "model" => "model319",
                "sku" => "sku319",
                "price" => 113,
                "origin_price" => 123,
                "cost_price" => 213,
                "quantity" => 33,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ],
            [
                "id" => 320,
                "product_id" => 4,
                "variants" => "[\"3\", \"1\"]",
                "position" => 7,
                "images" => null,
                "model" => "model320",
                "sku" => "sku320",
                "price" => 33,
                "origin_price" => 3123,
                "cost_price" => 3,
                "quantity" => 3123,
                "is_default" => 0,
                "created_at" => "2024-01-04 09:32:01",
                "updated_at" => "2024-01-04 09:32:01"
            ]
        ];
    }

    private function getProductRelations(): array
    {
        return [
            ["product_id" => 1, "relation_id" => 1,],
            ["product_id" => 1, "relation_id" => 2,],
            ["product_id" => 1, "relation_id" => 3,],
            ["product_id" => 1, "relation_id" => 5,],
            ["product_id" => 1, "relation_id" => 6,],
            ["product_id" => 1, "relation_id" => 8,],
            ["product_id" => 4, "relation_id" => 1,],
            ["product_id" => 4, "relation_id" => 2,],
            ["product_id" => 4, "relation_id" => 3,],
            ["product_id" => 4, "relation_id" => 4,],
            ["product_id" => 4, "relation_id" => 6,],
            ["product_id" => 4, "relation_id" => 7,],
            ["product_id" => 4, "relation_id" => 10,],
            ["product_id" => 6, "relation_id" => 1,],
            ["product_id" => 6, "relation_id" => 2,],
            ["product_id" => 6, "relation_id" => 4,],
            ["product_id" => 6, "relation_id" => 10,],
            ["product_id" => 39, "relation_id" => 1,],
            ["product_id" => 39, "relation_id" => 2,],
            ["product_id" => 39, "relation_id" => 3,],
            ["product_id" => 39, "relation_id" => 4,],
            ["product_id" => 39, "relation_id" => 5,],
            ["product_id" => 39, "relation_id" => 7,],
            ["product_id" => 39, "relation_id" => 9,],
            ["product_id" => 35, "relation_id" => 1,],
            ["product_id" => 35, "relation_id" => 2,],
            ["product_id" => 35, "relation_id" => 3,],
            ["product_id" => 35, "relation_id" => 4,],
            ["product_id" => 35, "relation_id" => 7,],
            ["product_id" => 35, "relation_id" => 8,],
            ["product_id" => 35, "relation_id" => 10,],
            ["product_id" => 15, "relation_id" => 1,],
            ["product_id" => 15, "relation_id" => 2,],
            ["product_id" => 15, "relation_id" => 3,],
            ["product_id" => 15, "relation_id" => 8,],
            ["product_id" => 15, "relation_id" => 9,],
            ["product_id" => 14, "relation_id" => 10,],
            ["product_id" => 14, "relation_id" => 9,],
            ["product_id" => 14, "relation_id" => 8,],
            ["product_id" => 14, "relation_id" => 7,],
            ["product_id" => 14, "relation_id" => 6,],
            ["product_id" => 14, "relation_id" => 5,],
            ["product_id" => 13, "relation_id" => 7,],
            ["product_id" => 13, "relation_id" => 10,],
            ["product_id" => 13, "relation_id" => 9,],
            ["product_id" => 13, "relation_id" => 8,],
            ["product_id" => 13, "relation_id" => 4,],
            ["product_id" => 13, "relation_id" => 2,],
            ["product_id" => 12, "relation_id" => 5,],
            ["product_id" => 12, "relation_id" => 1,],
            ["product_id" => 12, "relation_id" => 2,],
            ["product_id" => 12, "relation_id" => 9,],
            ["product_id" => 12, "relation_id" => 10,],
            ["product_id" => 12, "relation_id" => 7,],
            ["product_id" => 11, "relation_id" => 1,],
            ["product_id" => 11, "relation_id" => 2,],
            ["product_id" => 11, "relation_id" => 3,],
            ["product_id" => 11, "relation_id" => 7,],
            ["product_id" => 11, "relation_id" => 9,],
            ["product_id" => 10, "relation_id" => 9,],
            ["product_id" => 10, "relation_id" => 6,],
            ["product_id" => 10, "relation_id" => 10,],
            ["product_id" => 10, "relation_id" => 4,],
            ["product_id" => 10, "relation_id" => 1,],
            ["product_id" => 10, "relation_id" => 7,],
            ["product_id" => 9, "relation_id" => 2,],
            ["product_id" => 9, "relation_id" => 4,],
            ["product_id" => 9, "relation_id" => 8,],
            ["product_id" => 9, "relation_id" => 9,],
            ["product_id" => 9, "relation_id" => 10,],
            ["product_id" => 8, "relation_id" => 1,],
            ["product_id" => 8, "relation_id" => 2,],
            ["product_id" => 8, "relation_id" => 3,],
            ["product_id" => 8, "relation_id" => 4,],
            ["product_id" => 8, "relation_id" => 9,],
            ["product_id" => 7, "relation_id" => 5,],
            ["product_id" => 7, "relation_id" => 8,],
            ["product_id" => 7, "relation_id" => 10,],
            ["product_id" => 7, "relation_id" => 4,],
            ["product_id" => 7, "relation_id" => 1,],
            ["product_id" => 5, "relation_id" => 1,],
            ["product_id" => 5, "relation_id" => 6,],
            ["product_id" => 5, "relation_id" => 9,],
            ["product_id" => 5, "relation_id" => 10,],
            ["product_id" => 5, "relation_id" => 7,],
            ["product_id" => 3, "relation_id" => 2,],
            ["product_id" => 3, "relation_id" => 8,],
            ["product_id" => 3, "relation_id" => 9,],
            ["product_id" => 3, "relation_id" => 10,],
            ["product_id" => 3, "relation_id" => 4,]
        ];
    }
}
